### PR TITLE
"Big" Update!

### PR DESCRIPTION
**Pull request by ghost**
Hello zyenapz, i'm Danix. I'm know you know me, i'm the author of the original ["Big" Update](github.com/zyenapz/Caffeine-Fueled/pull/1) that you closed for _personal reasons_ but i saw "i will code the update and when you're not busy, you can view it". Well, there is it! The "Big" Update! The changes are the sames to the another pull request, but there are some different things:
1. The GameData class has removed due to the save system change.
2. The version of the update is 2.0.0.
3. I don't made the GitHub release tag, that you have to do it yourself.

Well, i know you canceled the colaboration due to you _personal resons_ but i understand you, i say again, when you can, view my pull request. If you accept my pull request, i wan't to ask you something, i wan't to make appear the Caffeine Fueled itch.io page in my itch.io profile but i need you to do something: add me as a Caffeine Fueled contributor. To do that, make this steps:
1. Enter the Caffeine Fueled dashboard.
2. Click More/Admins.
3. Enter my username (Danix421) and click Add admin.
4. Please, wait for me to accept your request to be an admin.
5. I think, after that, in the same webpage, will have to be a selection box or something that say "Contributor", if that appear you, click it.

I think this give me access to modify the Caffeine Fueled webpage, but i don't wan't that, i only wan't to make appear Caffeine Fueled in my itch.io profile. If you don't trust me, in all moment (i think) you can erase my access.
Well, i hope you like my pull request (and, obviously, __accept it__).

### CODE REVIEW

**Comment by ghost** [comment]
There is a error while saving, i will close this pull request, for now.

**Comment by ghost** [comment]
The error was in the Windows executable. (I think that) pyinstaller scans the game.py code and insert the save file to the executable and make that it can't be modified. If you accept this pull request, due to some personal reasons, you will have to re-made the Windows executable and that removes the Windows 32bits support

**Comment by fmtayag** [comment]
Danix...no. Let me be blunt to you now and say that I am **NOT** accepting or welcoming any contributions to the game (as I intended to say in my earlier posts). I tried to be nice in the earlier post about rejecting your wanting to contribute but it seems the intent was lost in the wording or the translation.

You probably spent hours trying to re-implement the saving system, among other things, so I apologize for all the trouble you went to and the time that you spent.

I appreciate your enthusiasm and I want to emphasize that you are welcome to study and modify my code but to re-iterate: I will not be accepting any contributions. I'm sorry again for the misunderstanding I have caused.

**Comment by fmtayag** [comment]
Just something I would like to add. I want to give you some advice so that your contributions and hours spent weren't for naught. I want to give you some feedback on what you could have improved in your contribution:

1. The time.sleep() method in the splash screens is not a good way of doing it because pygame's event listener is still active. If you press [ENTER] or [RETURN] during the splash screens for example, it would instantly take you to the game screen instead of the menu screen.
2. Use the 'pickle' library if you want to store and load data. It will be more convenient.
3. This will sound petty, but if you are contributing with someone, please refrain from calling their logo 'annoying' or something to that effect. I did not appreciate that fact one bit. 

With that said, this is not an invite for you to contribute again. I re-iterate that I am **NOT** accepting or welcoming contributions but you are welcome to study and modify the source code on your own (or the various permissions that the game's license grants you).

**Comment by ghost** [comment]
Sorry, zyenapz, that is some sad for me but i understand you, thanks for let's me know it! I hope you make some good games!

**Comment by ghost** [comment]
If in a near future, you need help, contact me. You're welcome!

**Pull request closed without merging**
